### PR TITLE
November 2018 Update

### LINKED ISSUE #32: Content update scheduled
This workshop is scheduled for an update. Please review the contents of this repo and comment on this issue with suggested updates. All suggestions must be added to this issue by EOD 11/9/18.

### PR DESCRIPTION
**Pull request by mrfalafel**
The November 2018 update is complete ready for review. Closes #32

### CODE REVIEW

**Comment by ezwiefel** [comment]
A few questions after a quick review. It appears that we've removed realtime scoring from the HOL, is that correct? If so, then what is the WebApp demonstrating that just using PowerBI wouldn't? 

I'd suggest we either:
* incorporate AML Services and publish a REST API for the webservice that way
* cut the webapp optional entirely... because you're asking for a URL (for scoring) that doesn't exist...

I'd also suggest splitting the monolithic `*.md` files into files by chapter. That would make completing the lab easier for users.

**Comment by mrfalafel** [comment]
Thank you for the quick review.
The real time scoring is implemented fully in the 3rd notebook part of the DBC included with the lab files and explained in details how to deploy the web service from Databricks.  The final Web app uses the scoring URI from that web service deployment.
Regarding the monolithic md files, unfortunately that is out of scope as we have a standard structure for these MCW's.
Thanks again for your feedback

**Comment by DawnmarieDesJardins** [comment]
@ZoinerTejada @mrfalafel 
Hello gentlemen,
We have sign off from our lead to finalize this update.  Please make sure that the comments above, and the open issues #30 & #31  have been addressed and let me know when the update is ready to QC/merge.  I'll need copies of the compliance checks and a new compliance doc for our files.

**Comment by mrfalafel** [comment]
The open issues have been resolved and the update is ready to QC/Merge.  Thanks!
We are always asked to deliver the compliance docs in a DropBox folder according to instructions from Kyle at Solliance. The compliance docs have been there for over a month. If the procedure changed please let me know and I can email you the compliance docs
Thanks for your help with this update!
-Lino

**Pull request merged**
